fix(nginx-agent) startup failed issue.
exception: Normal scoped bean class com.jslsolucoes.nginx.admin.agent.resource.impl.status.NginxStatusDiscover is not proxyable because it has no no-args constructor